#!/usr/bin/env python3
"""Write the Monroe tables shared by the firmware and the web renderer.

Single source of truth: ``robot_lipsync/monroe.py``. Pure Python.

- firmware/esp32_oled/monroe_select.h: nearest-frame choice from channels,
  so the board picks the same frame as the preview when no frame hint is sent;
- src/robot_lipsync/renderers/monroe_model.js: muscle targets, Mandarin glides,
  viseme map and frame names for the web renderer.

    python tools/monroe/build_tables.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from robot_lipsync import monroe  # noqa: E402


def main() -> None:
    ch = monroe.CHANNELS
    w = monroe._FRAME_WEIGHTS
    rows = []
    for key, pose in monroe.TARGETS.items():
        vals = ", ".join(f"{getattr(pose, c):.4f}f" for c in ch)
        rows.append(f"    {{{vals}}},  // {monroe.FRAME_INDEX['V2_' + key]}: {key}")
    text = f"""#pragma once
// Generated by tools/monroe/build_tables.py from robot_lipsync/monroe.py; do not edit.
// Picks the Monroe v2 frame (27..43) nearest to the streamed articulation.
#include <math.h>

#define MONROE_V2_FIRST {monroe.V2_FIRST_FRAME}
#define MONROE_V2_COUNT {len(monroe.TARGETS)}
#define MONROE_CHANNELS {len(ch)}
// channel order: {", ".join(ch)}
static const float MONROE_TARGETS[MONROE_V2_COUNT][MONROE_CHANNELS] = {{
{chr(10).join(rows)}
}};
static const float MONROE_WEIGHTS[MONROE_CHANNELS] = {{{", ".join(f"{w[c]:.2f}f" for c in ch)}}};

static inline float monroeClamp(float v, float lo, float hi) {{ return v < lo ? lo : (v > hi ? hi : v); }}

// jaw, separation, width, round, press, protrusion, tuck, asymmetry -> 11 muscle channels
static inline void monroeMuscles(float jaw, float sep, float width, float rnd, float press,
                                 float prot, float tuck, float asym, float out[MONROE_CHANNELS]) {{
  float upper = monroeClamp(0.40f * sep + 0.18f * tuck - 0.10f * press + 0.15f * prot, 0.0f, 1.0f);
  float lower = monroeClamp((jaw - 0.35f) * 1.55f, 0.0f, 1.0f);
  float corner = monroeClamp((width - 0.70f) * 0.75f, 0.0f, 0.30f);
  jaw = monroeClamp(jaw, 0.0f, 1.0f); sep = monroeClamp(sep, 0.0f, 1.0f); width = monroeClamp(width, 0.0f, 1.0f);
  press = monroeClamp(press, 0.0f, 1.0f); rnd = monroeClamp(rnd, 0.0f, 1.0f); prot = monroeClamp(prot, 0.0f, 1.0f);
  if (jaw > 0.52f) width = fminf(width, 0.72f - 0.42f * ((jaw - 0.52f) / 0.48f));
  if (width > 0.72f) jaw = fminf(jaw, 0.48f - 0.24f * ((width - 0.72f) / 0.28f));
  sep *= 1.0f - 0.96f * press;
  jaw *= 1.0f - 0.80f * press;
  width = fminf(width, 1.0f - 0.32f * rnd - 0.16f * prot);
  out[0] = monroeClamp(jaw, 0.0f, 1.0f); out[1] = monroeClamp(sep, 0.0f, 1.0f); out[2] = monroeClamp(width, 0.0f, 1.0f);
  out[3] = rnd; out[4] = prot; out[5] = upper; out[6] = lower; out[7] = press;
  out[8] = monroeClamp(tuck, 0.0f, 1.0f); out[9] = corner; out[10] = monroeClamp(asym, -1.0f, 1.0f);
}}

static inline int monroeNearestFrame(const float m[MONROE_CHANNELS]) {{
  int best = 0; float bestD = 1e30f;
  for (int i = 0; i < MONROE_V2_COUNT; ++i) {{
    float d = 0.0f;
    for (int c = 0; c < MONROE_CHANNELS; ++c) {{
      const float diff = m[c] - MONROE_TARGETS[i][c];
      d += MONROE_WEIGHTS[c] * diff * diff;
    }}
    if (d < bestD) {{ bestD = d; best = i; }}
  }}
  return MONROE_V2_FIRST + best;
}}
"""
    out = ROOT / "firmware/esp32_oled/monroe_select.h"
    out.write_text(text, encoding="utf-8")

    import json
    from dataclasses import asdict

    def muscles(table):
        return {k: {c: round(v, 4) for c, v in asdict(p).items() if c != "key"} for k, p in table.items()}

    model = {
        "channels": list(ch),
        "targets": muscles(monroe.TARGETS),
        "zhTargets": muscles(monroe.ZH_TARGETS),
        "zhGlides": monroe.ZH_GLIDES,
        "visemeTargets": monroe.VISEME_TARGETS,
        "frameNames": list(monroe.FRAME_NAMES),
        "frameWeights": monroe._FRAME_WEIGHTS,
        "v2First": monroe.V2_FIRST_FRAME,
    }
    js = ROOT / "src/robot_lipsync/renderers/monroe_model.js"
    js.write_text(
        "// Monroe muscle model tables (generated by tools/monroe/build_tables.py from monroe.py; do not edit).\n"
        "(function (root) { root.MONROE_MODEL = " + json.dumps(model, ensure_ascii=False) + "; })"
        "(typeof window !== \"undefined\" ? window : globalThis);\n",
        encoding="utf-8",
    )
    print(out, js)


if __name__ == "__main__":
    main()
