#!/usr/bin/env python3
"""Build the 44-frame Monroe bank used by the OLED firmware and the web renderer.

Frames 0..26 come from ``make_lips.py`` (Monroe v1); frames 27..43 from
``make_v2.py`` (muscle-channel targets). Requires Pillow and NumPy; the runtime
package itself has no dependencies.

    python tools/monroe/build_bank.py
"""

from __future__ import annotations

import base64
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(HERE))

import make_lips as v1  # noqa: E402
import make_v2 as v2  # noqa: E402


def main() -> None:
    frames, names = [], []
    for pose in v1.POSES:
        frames.append(v1.make_frame(pose))
        names.append("V1_" + pose.key)
    for key, pose in v2.TARGETS.items():
        frames.append(v2.render_frame(pose))
        names.append("V2_" + key)
    packed = [v1.pack_gfx_bitmap(f).tobytes() for f in frames]

    header = ROOT / "firmware/esp32_oled/monroe_frames.h"
    lines = [
        "#pragma once",
        "",
        "// Monroe lips frame bank: v1 (0..26) + muscle-channel v2 (27..43).",
        "// Generated by tools/monroe/build_bank.py. 128x64, Adafruit_GFX MSB-first bitmaps.",
        f"#define MONROE_FRAME_COUNT {len(frames)}",
        "",
    ]
    lines += [f"#define MONROE_{name} {i}" for i, name in enumerate(names)]
    lines += ["", "static const unsigned char PROGMEM MONROE_FRAMES[MONROE_FRAME_COUNT][1024] = {"]
    for i, (name, data) in enumerate(zip(names, packed, strict=True)):
        lines.append(f"  {{  // {i}: {name}")
        for start in range(0, len(data), 16):
            lines.append("    " + ",".join(f"0x{b:02X}" for b in data[start:start + 16]) + ",")
        lines.append("  },")
    lines += ["};", ""]
    header.write_text("\n".join(lines), encoding="utf-8")

    js = ROOT / "src/robot_lipsync/renderers/monroe_frames.js"
    payload = {"names": names, "frames": [base64.b64encode(b).decode() for b in packed]}
    js.write_text(
        "// Monroe lips frame bank (generated by tools/monroe/build_bank.py; do not edit).\n"
        "(function (root) { root.MONROE_BANK = " + json.dumps(payload) + "; })"
        "(typeof window !== \"undefined\" ? window : globalThis);\n",
        encoding="utf-8",
    )
    print(f"frames={len(frames)} header={header} js={js}")


if __name__ == "__main__":
    main()
