"""Lessons: an article cut into sentences, plus the steps of explaining it.

A lesson is plain JSON so it can be written by hand, generated by a model, or
edited after generation::

    {
      "title": "...", "source": "...",
      "language": "en", "explain_language": "zh-CN",
      "paragraphs": [{"text": "..."}, ...],            # or {"sentences": [...]}
      "steps": [
        {"say": "...", "focus": "p2.s1", "mark": "150", "note": "..."},
        ...
      ],
      "questions": [                                   # optional scripted answers
        {"match": ["word order", "语序"], "steps": [...]}
      ]
    }

Sentence ids are ``p<paragraph>.s<sentence>``, both counted from 1.
``mark`` circles a phrase inside the focused sentence (or ``{"sentence", "phrase"}``).
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

_SENTENCE_END = re.compile(r"(?<=[.!?。！？…])[\"'”’)\]]*\s+(?=[\"'“‘(\[]?[A-Z0-9㐀-鿿])|(?<=[。！？])")
_ABBREVIATIONS = ("e.g.", "i.e.", "et al.", "Dr.", "Mr.", "Mrs.", "Ms.", "St.", "vs.", "Fig.", "No.")


def split_sentences(text: str) -> list[str]:
    text = re.sub(r"\s+", " ", text.strip())
    if not text:
        return []
    parts, buffer = [], ""
    for piece in _SENTENCE_END.split(text):
        if not piece:
            continue
        buffer = f"{buffer} {piece}".strip() if buffer else piece.strip()
        if buffer.endswith(_ABBREVIATIONS):
            continue
        parts.append(buffer)
        buffer = ""
    if buffer:
        parts.append(buffer)
    return parts


FIGURE_TYPES = ("compare", "flow", "timeline", "terms")


def clean_figure(fig: Any) -> dict[str, Any] | None:
    """A small diagram the e-reader draws with boxes and lines (no images).

    compare:  {"rows": [{"label", "items": [...], "hi": [index, ...]}]}   e.g. word orders side by side
    flow:     {"items": ["a", "b", "c"]}                                  a → b → c
    timeline: {"items": [{"when", "what"}]}
    terms:    {"items": [{"term", "meaning"}]}
    Every type also takes a short "title". Anything malformed is dropped, long text is cut."""

    if not isinstance(fig, dict) or fig.get("type") not in FIGURE_TYPES:
        return None

    def cut(value: Any, n: int) -> str:
        return str(value if value is not None else "").strip()[:n]

    kind, out = fig["type"], {"type": fig["type"], "title": cut(fig.get("title"), 40)}
    if kind == "compare":
        rows = []
        for row in (fig.get("rows") or [])[:4]:
            if not isinstance(row, dict):
                continue
            items = [cut(x, 14) for x in (row.get("items") or [])[:6] if cut(x, 14)]
            hi = row.get("hi")
            hi = hi if isinstance(hi, list) else [hi]
            if items:
                rows.append({"label": cut(row.get("label"), 20), "items": items,
                             "hi": [i for i in hi if isinstance(i, int) and 0 <= i < len(items)]})
        out["rows"] = rows
        return out if rows else None
    raw = fig.get("items") or []
    if kind == "flow":
        out["items"] = [cut(x, 24) for x in raw[:5] if cut(x, 24)]
        return out if len(out["items"]) >= 2 else None
    if kind == "timeline":
        out["items"] = [{"when": cut(i.get("when"), 12), "what": cut(i.get("what"), 40)}
                        for i in raw[:5] if isinstance(i, dict) and cut(i.get("what"), 40)]
    else:
        out["items"] = [{"term": cut(i.get("term"), 24), "meaning": cut(i.get("meaning"), 44)}
                        for i in raw[:4] if isinstance(i, dict) and cut(i.get("term"), 24)]
    return out if out["items"] else None


@dataclass
class Step:
    say: str = ""
    focus: str | None = None
    mark: dict[str, str] | None = None
    note: str | None = None
    clear_note: bool = False
    pause: float = 0.0
    figure: dict[str, Any] | None = None
    cue: str | None = None        # tell other programs to do something now (open a video, move a robot)

    @classmethod
    def from_dict(cls, data: dict[str, Any], current: str | None = None) -> Step:
        focus = data.get("focus") or None
        mark = data.get("mark")
        if isinstance(mark, str):
            mark = {"sentence": focus or current, "phrase": mark}
        return cls(
            say=str(data.get("say", "")).strip(),
            focus=focus,
            mark=mark,
            note=(str(data["note"]).strip() if data.get("note") else None),
            clear_note=bool(data.get("clear_note", False)),
            pause=float(data.get("pause", 0.0)),
            figure=clean_figure(data.get("figure")),
            cue=(str(data["cue"]).strip()[:40] or None) if data.get("cue") else None,
        )

    def to_dict(self) -> dict[str, Any]:
        out: dict[str, Any] = {"say": self.say}
        for key in ("focus", "mark", "note", "figure", "cue"):
            if getattr(self, key):
                out[key] = getattr(self, key)
        if self.clear_note:
            out["clear_note"] = True
        if self.pause:
            out["pause"] = self.pause
        return out


@dataclass
class Lesson:
    title: str
    paragraphs: list[list[str]]
    steps: list[Step]
    source: str = ""
    language: str = "en"
    explain_language: str = "en"
    questions: list[dict[str, Any]] = field(default_factory=list)
    cues: dict[str, str] = field(default_factory=dict)   # name -> what it shows, for the model to choose

    # ---- ids -------------------------------------------------------------------------
    def sentence_ids(self) -> list[str]:
        return [f"p{p + 1}.s{s + 1}" for p, para in enumerate(self.paragraphs) for s in range(len(para))]

    def sentence(self, sid: str) -> str:
        match = re.fullmatch(r"p(\d+)\.s(\d+)", sid or "")
        if not match:
            raise KeyError(sid)
        p, s = int(match.group(1)) - 1, int(match.group(2)) - 1
        if not (0 <= p < len(self.paragraphs) and 0 <= s < len(self.paragraphs[p])):
            raise KeyError(sid)
        return self.paragraphs[p][s]

    def reader_payload(self) -> dict[str, Any]:
        """What the e-reader needs to lay out the article."""

        return {
            "title": self.title,
            "source": self.source,
            "steps": len(self.steps),
            "paragraphs": [
                {"id": f"p{p + 1}", "sentences": [{"id": f"p{p + 1}.s{s + 1}", "text": t} for s, t in enumerate(para)]}
                for p, para in enumerate(self.paragraphs)
            ],
        }

    def context(self, upto: int | None = None) -> str:
        """The article with sentence ids, for prompting a model."""

        lines = [f"# {self.title}"]
        for p, para in enumerate(self.paragraphs):
            lines.append(" ".join(f"[p{p + 1}.s{s + 1}] {t}" for s, t in enumerate(para)))
        return "\n\n".join(lines)

    # ---- validation ------------------------------------------------------------------
    def problems(self) -> list[str]:
        ids, issues = set(self.sentence_ids()), []
        for kind, steps in [("step", self.steps)] + [
            (f"question {i + 1}", [Step.from_dict(s) for s in q.get("steps", [])]) for i, q in enumerate(self.questions)
        ]:
            current = None
            for n, step in enumerate(steps, 1):
                if step.focus:
                    if step.focus not in ids:
                        issues.append(f"{kind} {n}: unknown sentence {step.focus}")
                    current = step.focus
                if step.mark:
                    sid = step.mark.get("sentence") or current
                    phrase = step.mark.get("phrase", "")
                    if sid not in ids:
                        issues.append(f"{kind} {n}: mark on unknown sentence {sid}")
                    elif phrase and phrase not in self.sentence(sid):
                        issues.append(f"{kind} {n}: '{phrase}' is not in {sid}")
        return issues

    # ---- io --------------------------------------------------------------------------
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Lesson:
        paragraphs = []
        for para in data["paragraphs"]:
            if isinstance(para, str):
                para = {"text": para}
            sentences = para.get("sentences") or split_sentences(para.get("text", ""))
            if sentences:
                paragraphs.append([s.strip() for s in sentences if s.strip()])
        steps, current = [], None
        for raw in data.get("steps", []):
            step = Step.from_dict(raw, current)
            current = step.focus or current
            steps.append(step)
        return cls(
            title=data.get("title", "Untitled"),
            paragraphs=paragraphs,
            steps=steps,
            source=data.get("source", ""),
            language=data.get("language", "en"),
            explain_language=data.get("explain_language", data.get("language", "en")),
            questions=list(data.get("questions", [])),
            cues={str(k): str(v) for k, v in (data.get("cues") or {}).items()},
        )

    @classmethod
    def load(cls, path: str | Path) -> Lesson:
        return cls.from_dict(json.loads(Path(path).read_text(encoding="utf-8")))

    def to_dict(self) -> dict[str, Any]:
        return {
            "title": self.title,
            "source": self.source,
            "language": self.language,
            "explain_language": self.explain_language,
            "paragraphs": [{"sentences": para} for para in self.paragraphs],
            "steps": [s.to_dict() for s in self.steps],
            "questions": self.questions,
            **({"cues": self.cues} if self.cues else {}),
        }

    def save(self, path: str | Path) -> None:
        Path(path).write_text(json.dumps(self.to_dict(), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
