#pragma once
// Generated by tools/mouth/build_tables.py from robot_lipsync/mouth.py; do not edit.
// Picks the Mouth v2 frame (27..43) nearest to the streamed articulation.
#include <math.h>

#define MOUTH_V2_FIRST 27
#define MOUTH_V2_COUNT 17
#define MOUTH_CHANNELS 11
// channel order: jaw_open, lip_separation, mouth_width, lip_round, lip_protrusion, upper_lip_raise, lower_lip_depress, lip_press, lower_lip_tuck, corner_raise, asymmetry
static const float MOUTH_TARGETS[MOUTH_V2_COUNT][MOUTH_CHANNELS] = {
    {0.0000f, 0.0310f, 0.5200f, 0.0400f, 0.0200f, 0.0400f, 0.0400f, 0.1200f, 0.0000f, 0.0000f, 0.0000f},  // 27: REST
    {0.0000f, 0.0000f, 0.4600f, 0.1400f, 0.1000f, 0.0400f, 0.0400f, 1.0000f, 0.0000f, 0.0000f, 0.0000f},  // 28: PRESS_MBP
    {0.1000f, 0.1500f, 0.5700f, 0.0400f, 0.0200f, 0.1800f, 0.0400f, 0.0000f, 1.0000f, 0.0000f, -0.0500f},  // 29: FV_TUCK
    {0.1400f, 0.2200f, 0.5900f, 0.0400f, 0.0200f, 0.1200f, 0.1000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},  // 30: TH_DH
    {0.1500f, 0.2200f, 0.5300f, 0.0400f, 0.0200f, 0.0400f, 0.0400f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},  // 31: SOFT
    {0.2400f, 0.3100f, 0.9600f, 0.0400f, 0.0200f, 0.1300f, 0.0400f, 0.0000f, 0.0000f, 0.2000f, 0.0000f},  // 32: WIDE_I
    {0.3400f, 0.4300f, 0.8200f, 0.0400f, 0.0200f, 0.1700f, 0.0400f, 0.0000f, 0.0000f, 0.1000f, 0.0000f},  // 33: MID_E
    {0.6400f, 0.7200f, 0.6000f, 0.0400f, 0.0200f, 0.2800f, 0.5200f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},  // 34: OPEN_AE
    {0.7600f, 0.8200f, 0.5100f, 0.0400f, 0.0200f, 0.3100f, 0.6800f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},  // 35: OPEN_AH
    {1.0000f, 0.9600f, 0.3000f, 0.0400f, 0.0200f, 0.5000f, 1.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},  // 36: DEEP_AA
    {0.6600f, 0.7200f, 0.3600f, 0.8800f, 0.4000f, 0.2500f, 0.6000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},  // 37: ROUND_AO
    {0.4500f, 0.5200f, 0.3100f, 0.9000f, 0.6200f, 0.0400f, 0.3000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},  // 38: ROUND_OW
    {0.2500f, 0.3600f, 0.1800f, 1.0000f, 1.0000f, 0.0400f, 0.0400f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},  // 39: PUCKER_UW
    {0.3000f, 0.3800f, 0.2900f, 0.5800f, 0.6800f, 0.0400f, 0.0400f, 0.0000f, 0.0000f, 0.0000f, 0.0500f},  // 40: RHOTIC_ER
    {0.4800f, 0.6200f, 0.5500f, 0.0400f, 0.0200f, 0.2800f, 0.3600f, 0.0000f, 0.0000f, 0.0000f, 0.0400f},  // 41: BREATH_H
    {0.2600f, 0.3100f, 0.6800f, 0.0400f, 0.0200f, 0.1400f, 0.0400f, 0.0000f, 0.0000f, 0.1000f, -0.3400f},  // 42: SIDE_L
    {0.2900f, 0.3500f, 0.4800f, 0.3400f, 0.2500f, 0.1900f, 0.0400f, 0.0000f, 0.0000f, 0.0000f, 0.2000f},  // 43: SIDE_SH
};
static const float MOUTH_WEIGHTS[MOUTH_CHANNELS] = {2.00f, 1.60f, 1.60f, 1.40f, 0.80f, 0.50f, 0.70f, 2.40f, 2.00f, 0.60f, 0.60f};

static inline float mouthClamp(float v, float lo, float hi) { return v < lo ? lo : (v > hi ? hi : v); }

// jaw, separation, width, round, press, protrusion, tuck, asymmetry -> 11 muscle channels
static inline void mouthMuscles(float jaw, float sep, float width, float rnd, float press,
                                 float prot, float tuck, float asym, float out[MOUTH_CHANNELS]) {
  float upper = mouthClamp(0.40f * sep + 0.18f * tuck - 0.10f * press + 0.15f * prot, 0.0f, 1.0f);
  float lower = mouthClamp((jaw - 0.35f) * 1.55f, 0.0f, 1.0f);
  float corner = mouthClamp((width - 0.70f) * 0.75f, 0.0f, 0.30f);
  jaw = mouthClamp(jaw, 0.0f, 1.0f); sep = mouthClamp(sep, 0.0f, 1.0f); width = mouthClamp(width, 0.0f, 1.0f);
  press = mouthClamp(press, 0.0f, 1.0f); rnd = mouthClamp(rnd, 0.0f, 1.0f); prot = mouthClamp(prot, 0.0f, 1.0f);
  if (jaw > 0.52f) width = fminf(width, 0.72f - 0.42f * ((jaw - 0.52f) / 0.48f));
  if (width > 0.72f) jaw = fminf(jaw, 0.48f - 0.24f * ((width - 0.72f) / 0.28f));
  sep *= 1.0f - 0.96f * press;
  jaw *= 1.0f - 0.80f * press;
  width = fminf(width, 1.0f - 0.32f * rnd - 0.16f * prot);
  out[0] = mouthClamp(jaw, 0.0f, 1.0f); out[1] = mouthClamp(sep, 0.0f, 1.0f); out[2] = mouthClamp(width, 0.0f, 1.0f);
  out[3] = rnd; out[4] = prot; out[5] = upper; out[6] = lower; out[7] = press;
  out[8] = mouthClamp(tuck, 0.0f, 1.0f); out[9] = corner; out[10] = mouthClamp(asym, -1.0f, 1.0f);
}

static inline int mouthNearestFrame(const float m[MOUTH_CHANNELS]) {
  int best = 0; float bestD = 1e30f;
  for (int i = 0; i < MOUTH_V2_COUNT; ++i) {
    float d = 0.0f;
    for (int c = 0; c < MOUTH_CHANNELS; ++c) {
      const float diff = m[c] - MOUTH_TARGETS[i][c];
      d += MOUTH_WEIGHTS[c] * diff * diff;
    }
    if (d < bestD) { bestD = d; best = i; }
  }
  return MOUTH_V2_FIRST + best;
}
