#!/usr/bin/env python3
"""Write the Mouth tables shared by the firmware and the web renderer.

Single source of truth: ``robot_lipsync/mouth.py``. Pure Python.

- firmware/esp32_oled/mouth_select.h: nearest-frame choice from channels,
  so the board picks the same frame as the preview when no frame hint is sent;
- src/robot_lipsync/renderers/mouth_model.js: muscle targets, Mandarin glides,
  viseme map and frame names for the web renderer.

    python tools/mouth/build_tables.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from robot_lipsync import mouth  # noqa: E402


def main() -> None:
    ch = mouth.CHANNELS
    w = mouth._FRAME_WEIGHTS
    rows = []
    for key, pose in mouth.TARGETS.items():
        vals = ", ".join(f"{getattr(pose, c):.4f}f" for c in ch)
        rows.append(f"    {{{vals}}},  // {mouth.FRAME_INDEX['V2_' + key]}: {key}")
    text = f"""#pragma once
// Generated by tools/mouth/build_tables.py from robot_lipsync/mouth.py; do not edit.
// Picks the Mouth v2 frame (27..43) nearest to the streamed articulation.
#include <math.h>

#define MOUTH_V2_FIRST {mouth.V2_FIRST_FRAME}
#define MOUTH_V2_COUNT {len(mouth.TARGETS)}
#define MOUTH_CHANNELS {len(ch)}
// channel order: {", ".join(ch)}
static const float MOUTH_TARGETS[MOUTH_V2_COUNT][MOUTH_CHANNELS] = {{
{chr(10).join(rows)}
}};
static const float MOUTH_WEIGHTS[MOUTH_CHANNELS] = {{{", ".join(f"{w[c]:.2f}f" for c in ch)}}};

static inline float mouthClamp(float v, float lo, float hi) {{ return v < lo ? lo : (v > hi ? hi : v); }}

// jaw, separation, width, round, press, protrusion, tuck, asymmetry -> 11 muscle channels
static inline void mouthMuscles(float jaw, float sep, float width, float rnd, float press,
                                 float prot, float tuck, float asym, float out[MOUTH_CHANNELS]) {{
  float upper = mouthClamp(0.40f * sep + 0.18f * tuck - 0.10f * press + 0.15f * prot, 0.0f, 1.0f);
  float lower = mouthClamp((jaw - 0.35f) * 1.55f, 0.0f, 1.0f);
  float corner = mouthClamp((width - 0.70f) * 0.75f, 0.0f, 0.30f);
  jaw = mouthClamp(jaw, 0.0f, 1.0f); sep = mouthClamp(sep, 0.0f, 1.0f); width = mouthClamp(width, 0.0f, 1.0f);
  press = mouthClamp(press, 0.0f, 1.0f); rnd = mouthClamp(rnd, 0.0f, 1.0f); prot = mouthClamp(prot, 0.0f, 1.0f);
  if (jaw > 0.52f) width = fminf(width, 0.72f - 0.42f * ((jaw - 0.52f) / 0.48f));
  if (width > 0.72f) jaw = fminf(jaw, 0.48f - 0.24f * ((width - 0.72f) / 0.28f));
  sep *= 1.0f - 0.96f * press;
  jaw *= 1.0f - 0.80f * press;
  width = fminf(width, 1.0f - 0.32f * rnd - 0.16f * prot);
  out[0] = mouthClamp(jaw, 0.0f, 1.0f); out[1] = mouthClamp(sep, 0.0f, 1.0f); out[2] = mouthClamp(width, 0.0f, 1.0f);
  out[3] = rnd; out[4] = prot; out[5] = upper; out[6] = lower; out[7] = press;
  out[8] = mouthClamp(tuck, 0.0f, 1.0f); out[9] = corner; out[10] = mouthClamp(asym, -1.0f, 1.0f);
}}

static inline int mouthNearestFrame(const float m[MOUTH_CHANNELS]) {{
  int best = 0; float bestD = 1e30f;
  for (int i = 0; i < MOUTH_V2_COUNT; ++i) {{
    float d = 0.0f;
    for (int c = 0; c < MOUTH_CHANNELS; ++c) {{
      const float diff = m[c] - MOUTH_TARGETS[i][c];
      d += MOUTH_WEIGHTS[c] * diff * diff;
    }}
    if (d < bestD) {{ bestD = d; best = i; }}
  }}
  return MOUTH_V2_FIRST + best;
}}
"""
    out = ROOT / "firmware/esp32_oled/mouth_select.h"
    out.write_text(text, encoding="utf-8")

    import json
    from dataclasses import asdict

    def muscles(table):
        return {k: {c: round(v, 4) for c, v in asdict(p).items() if c != "key"} for k, p in table.items()}

    model = {
        "channels": list(ch),
        "targets": muscles(mouth.TARGETS),
        "zhTargets": muscles(mouth.ZH_TARGETS),
        "zhGlides": mouth.ZH_GLIDES,
        "langTargets": muscles(mouth.LANG_TARGETS),
        "glides": mouth.GLIDES,
        "visemeTargets": mouth.VISEME_TARGETS,
        "frameNames": list(mouth.FRAME_NAMES),
        "frameWeights": mouth._FRAME_WEIGHTS,
        "v2First": mouth.V2_FIRST_FRAME,
    }
    js = ROOT / "src/robot_lipsync/renderers/mouth_model.js"
    js.write_text(
        "// Mouth muscle model tables (generated by tools/mouth/build_tables.py from mouth.py; do not edit).\n"
        "(function (root) { root.MOUTH_MODEL = " + json.dumps(model, ensure_ascii=False) + "; })"
        "(typeof window !== \"undefined\" ? window : globalThis);\n",
        encoding="utf-8",
    )
    print(out, js)


if __name__ == "__main__":
    main()
